#include "WriteEnableForThreadsAt_ClientOutputReceive__Framework.h"
#include "../include/WriteEnableForThreadsAt_ClientOutputReceive__App.h"
#include "../include/WriteEnableForThreadsAt_ClientOutputReceive__Control.h"
#include "../include/WriteEnableForThreadsAt_ClientOutputReceive__Global.h"
#include <iostream>
CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__App* CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App;
CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Global* CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Global;
// public.
CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::WriteEnableForThreadsAt_ClientOutputReceive__Framework()
{
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__Framework();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__Framework();
}
CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::~WriteEnableForThreadsAt_ClientOutputReceive__Framework()
{
	delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App;
	delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Global;
}
CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__App* CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App();
}
CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Global* CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Global() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Global();
}
void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__Framework(WriteEnableForThreadsAt_ClientOutputReceive__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App__Control()->dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__Control(obj);
}
void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_ClientOutputReceive__Framework(WriteEnableForThreadsAt_ClientOutputReceive__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App__Control()->dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_ClientOutputReceive__Control(obj);
}
void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__Framework(WriteEnableForThreadsAt_ClientOutputReceive__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App__Control()->dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__Control(obj);
}
void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::dyn_boot4_PGM_INSTANTIATION_WriteEnableForThreadsAt_ClientOutputReceive__Framework(WriteEnableForThreadsAt_ClientOutputReceive__Framework* obj) {

}
void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__Framework() {
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__App();
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__Global();
}
void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__Framework() {
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__App();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__Global();
}
// private.
void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App = nullptr;
}
void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Global = NULL;
}
void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App = new class CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__App();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App() == nullptr) {}
}
void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Global = new class CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Global();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Global() == NULL) {}
}
CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__App* CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App()
{
	return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App;
}
CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Global* CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Global;
	}