#include "WriteEnableForThreadsAt_ClientOutputReceive__Framework.h"
CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__App* CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Framework__App;
	CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Global* CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Framework__Global;
// public.
	CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::WriteEnableForThreadsAt_ClientOutputReceive__Framework() {

	}
	CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::~WriteEnableForThreadsAt_ClientOutputReceive__Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Framework__Global;
	}
	void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ClientOutputReceive__Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__Framework();
	}
	void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ClientOutputReceive__Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__Global();
	}
	CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__App* CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App();
	}
	CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Global* CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Global();
	}
	void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__Global();
	}
	void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__App();
	}
	void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__Global();
	}
// private.
	void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Framework__App = nullptr;
	}
	void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientOutputReceive__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Framework__App = new class CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App() == nullptr) {}
	}
	void CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientOutputReceive__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Framework__Global = new class CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Global() == nullptr) {}
	}
	CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__App* CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Framework__App;
	}
	CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Global* CLIBWriteQueAtClientOutputReceive::WriteEnableForThreadsAt_ClientOutputReceive__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ClientOutputReceive__Framework__Global;
	}