#include "WriteEnableForThreadsAt_ClientUserOutput__Framework.h"
CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__App* CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserOutput__Framework__App;
	CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Global* CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientUserOutput__Framework__Global;
// public.
	CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::WriteEnableForThreadsAt_ClientUserOutput__Framework() {

	}
	CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::~WriteEnableForThreadsAt_ClientUserOutput__Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserOutput__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ClientUserOutput__Framework__Global;
	}
	void CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ClientUserOutput__Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientUserOutput__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserOutput__Framework();
	}
	void CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ClientUserOutput__Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientUserOutput__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserOutput__Global();
	}
	CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__App* CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserOutput__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserOutput__App();
	}
	CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Global* CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserOutput__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserOutput__Global();
	}
	void CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientUserOutput__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientUserOutput__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientUserOutput__Global();
	}
	void CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserOutput__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserOutput__App();
	}
	void CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserOutput__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserOutput__Global();
	}
// private.
	void CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientUserOutput__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserOutput__Framework__App = nullptr;
	}
	void CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientUserOutput__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientUserOutput__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserOutput__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserOutput__Framework__App = new class CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserOutput__App() == nullptr) {}
	}
	void CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserOutput__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientUserOutput__Framework__Global = new class CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserOutput__Global() == nullptr) {}
	}
	CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__App* CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserOutput__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserOutput__Framework__App;
	}
	CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Global* CLIBWriteQueAtClientUserOutput::WriteEnableForThreadsAt_ClientUserOutput__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserOutput__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ClientUserOutput__Framework__Global;
	}