#include "WriteEnableForThreadsAt_OutputGameInstanaceData__Framework.h"
#include "../include/WriteEnableForThreadsAt_OutputGameInstanaceData__App.h"
#include "../include/WriteEnableForThreadsAt_OutputGameInstanaceData__Control.h"
#include "../include/WriteEnableForThreadsAt_OutputGameInstanaceData__Global.h"
#include <iostream>
CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__App* CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App;
CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Global* CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__Global;
// public.
CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework()
{
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OutputGameInstanaceData__Framework();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OutputGameInstanaceData__Framework();
}
CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::~WriteEnableForThreadsAt_OutputGameInstanaceData__Framework()
{
	delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App;
	delete _stat_CLASS_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__Global;
}
CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__App* CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App();
}
CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Global* CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__Global() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__Global();
}
void CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_OutputGameInstanaceData__Framework(WriteEnableForThreadsAt_OutputGameInstanaceData__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App__Control()->dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_OutputGameInstanaceData__Control(obj);
}
void CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_OutputGameInstanaceData__Framework(WriteEnableForThreadsAt_OutputGameInstanaceData__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App__Control()->dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_OutputGameInstanaceData__Control(obj);
}
void CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_OutputGameInstanaceData__Framework(WriteEnableForThreadsAt_OutputGameInstanaceData__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App__Control()->dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_OutputGameInstanaceData__Control(obj);
}
void CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::dyn_boot4_PGM_INSTANTIATION_WriteEnableForThreadsAt_OutputGameInstanaceData__Framework(WriteEnableForThreadsAt_OutputGameInstanaceData__Framework* obj) {

}
void CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OutputGameInstanaceData__Framework() {
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OutputGameInstanaceData__App();
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OutputGameInstanaceData__Global();
}
void CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OutputGameInstanaceData__Framework() {
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OutputGameInstanaceData__App();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OutputGameInstanaceData__Global();
}
// private.
void CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OutputGameInstanaceData__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App = nullptr;
}
void CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OutputGameInstanaceData__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__Global = NULL;
}
void CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OutputGameInstanaceData__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App = new class CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__App();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App() == nullptr) {}
}
void CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OutputGameInstanaceData__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__Global = new class CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Global();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__Global() == NULL) {}
}
CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__App* CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App()
{
	return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__App;
}
CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Global* CLIBWriteQueAtCLIB_WriteQueForThreadAt_OutputGameInstanaceData::WriteEnableForThreadsAt_OutputGameInstanaceData__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_OutputGameInstanaceData__Global;
	}