#include "WriteEnableForThreadsAt_ConditionCode__Framework.h"
#include "../include/WriteEnableForThreadsAt_ConditionCode__Control.h"
#include <iostream>
CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__App* CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App;
CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Global* CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ConditionCode__Global;
// public.
CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::WriteEnableForThreadsAt_ConditionCode__Framework()
{
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ConditionCode__Framework();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ConditionCode__Framework();
}
CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::~WriteEnableForThreadsAt_ConditionCode__Framework()
{
	delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App;
	delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ConditionCode__Global;
}
CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__App* CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App();
}
CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Global* CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__Global() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__Global();
}
void CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_ConditionCode__Framework(WriteEnableForThreadsAt_ConditionCode__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App__Control()->dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_ConditionCode__Control(obj);
}
void CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_ConditionCode__Framework(WriteEnableForThreadsAt_ConditionCode__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App__Control()->dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_ConditionCode__Control(obj);
}
void CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_ConditionCode__Framework(WriteEnableForThreadsAt_ConditionCode__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App__Control()->dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_ConditionCode__Control(obj);
}
void CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::dyn_boot4_PGM_INSTANTIATION_WriteEnableForThreadsAt_ConditionCode__Framework(WriteEnableForThreadsAt_ConditionCode__Framework* obj) {

}
void CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ConditionCode__Framework() {
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ConditionCode__App();
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ConditionCode__Global();
}
void CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ConditionCode__Framework() {
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ConditionCode__App();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ConditionCode__Global();
}
// private.
void CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ConditionCode__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App = nullptr;
}
void CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ConditionCode__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_ConditionCode__Global = NULL;
}
void CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ConditionCode__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App = new class CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__App();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App() == nullptr) {}
}
void CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ConditionCode__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_ConditionCode__Global = new class CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Global();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__Global() == NULL) {}
}
CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__App* CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App()
{
	return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__App;
}
CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Global* CLIBWriteQueAtConditionCode::WriteEnableForThreadsAt_ConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ConditionCode__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ConditionCode__Global;
	}