#include "WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework.h"
#include "../include/WriteEnableForThreadsAt_SIMULATION_InputSamples__App.h"
#include "../include/WriteEnableForThreadsAt_SIMULATION_InputSamples__Control.h"
#include "../include/WriteEnableForThreadsAt_SIMULATION_InputSamples__Global.h"
#include <iostream>
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__App* CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App;
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Global* CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__Global;
// public.
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework()
{
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework();
}
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::~WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework()
{
	delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App;
	delete _stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__Global;
}
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__App* CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App();
}
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Global* CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__Global() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__Global();
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework(WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App__Control()->dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_InputSamples__Control(obj);
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework(WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App__Control()->dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_SIMULATION_InputSamples__Control(obj);
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework(WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App__Control()->dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_InputSamples__Control(obj);
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::dyn_boot4_PGM_INSTANTIATION_WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework(WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework* obj) {

}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework() {
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_InputSamples__App();
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_InputSamples__Global();
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework() {
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_InputSamples__App();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_InputSamples__Global();
}
// private.
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_InputSamples__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App = nullptr;
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_InputSamples__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__Global = NULL;
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_InputSamples__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App = new class CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__App();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App() == nullptr) {}
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_InputSamples__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__Global = new class CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Global();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__Global() == NULL) {}
}
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__App* CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App()
{
	return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__App;
}
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Global* CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION_InputSamples__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION_InputSamples__Global;
	}