#include "WriteEnableForThreadsAt_ClientInputSend__Framework.h"
CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__App* CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__Framework__App;
	CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Global* CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientInputSend__Framework__Global;
// public.
	CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::WriteEnableForThreadsAt_ClientInputSend__Framework() {

	}
	CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::~WriteEnableForThreadsAt_ClientInputSend__Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ClientInputSend__Framework__Global;
	}
	void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ClientInputSend__Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__Framework();
	}
	void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ClientInputSend__Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__Global();
	}
	CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__App* CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App();
	}
	CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Global* CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__Global();
	}
	void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__Global();
	}
	void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__App();
	}
	void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__Global();
	}
// private.
	void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__Framework__App = nullptr;
	}
	void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientInputSend__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__Framework__App = new class CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App() == nullptr) {}
	}
	void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientInputSend__Framework__Global = new class CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__Global() == nullptr) {}
	}
	CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__App* CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__Framework__App;
	}
	CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Global* CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ClientInputSend__Framework__Global;
	}