#include "WriteEnableForThreadsAt_ClientInputSend__Framework.h"
#include "../include/WriteEnableForThreadsAt_ClientInputSend__Control.h"
#include <iostream>
CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__App* CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App;
CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Global* CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientInputSend__Global;
// public.
CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::WriteEnableForThreadsAt_ClientInputSend__Framework()
{
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__Framework();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__Framework();
}
CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::~WriteEnableForThreadsAt_ClientInputSend__Framework()
{
	delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App;
	delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ClientInputSend__Global;
}
CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__App* CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App();
}
CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Global* CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__Global() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__Global();
}
void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__Framework(WriteEnableForThreadsAt_ClientInputSend__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App__Control()->dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__Control(obj);
}
void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_ClientInputSend__Framework(WriteEnableForThreadsAt_ClientInputSend__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App__Control()->dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_ClientInputSend__Control(obj);
}
void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__Framework(WriteEnableForThreadsAt_ClientInputSend__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App__Control()->dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__Control(obj);
}
void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::dyn_boot4_PGM_INSTANTIATION_WriteEnableForThreadsAt_ClientInputSend__Framework(WriteEnableForThreadsAt_ClientInputSend__Framework* obj) {

}
void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__Framework() {
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__App();
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__Global();
}
void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__Framework() {
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__App();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__Global();
}
// private.
void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App = nullptr;
}
void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientInputSend__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientInputSend__Global = NULL;
}
void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App = new class CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__App();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App() == nullptr) {}
}
void CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientInputSend__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientInputSend__Global = new class CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Global();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__Global() == NULL) {}
}
CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__App* CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App()
{
	return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__App;
}
CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Global* CLIBWriteQueAtClientInputSend::WriteEnableForThreadsAt_ClientInputSend__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientInputSend__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ClientInputSend__Global;
	}