#include "WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework.h"
#include "../include/WriteEnableForThreadsAt_SIMULATION_OutputSamples__Control.h"
#include <iostream>
CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__App* CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App;
CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global* CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global;
// public.
CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework()
{
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework();
}
CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::~WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework()
{
	delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App;
	delete _stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global;
}
CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__App* CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App();
}
CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global* CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global();
}
void CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework(WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App__Control()->dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Control(obj);
}
void CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework(WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App__Control()->dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Control(obj);
}
void CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework(WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App__Control()->dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Control(obj);
}
void CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::dyn_boot4_PGM_INSTANTIATION_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework(WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework* obj) {

}
void CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework() {
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App();
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global();
}
void CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework() {
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global();
}
// private.
void CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App = nullptr;
}
void CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global = NULL;
}
void CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App = new class CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__App();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App() == nullptr) {}
}
void CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global = new class CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global() == NULL) {}
}
CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__App* CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App()
{
	return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__App;
}
CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global* CLIBWriteQueAtSIMULATION_OutputSamples::WriteEnableForThreadsAt_SIMULATION_OutputSamples__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION_OutputSamples__Global;
	}