#include "WriteEnableForThreadsAt_SimulationIO__Framework.h"
CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__App* CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_SimulationIO__Framework__App;
	CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Global* CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_SimulationIO__Framework__Global;
// public.
	CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::WriteEnableForThreadsAt_SimulationIO__Framework() {

	}
	CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::~WriteEnableForThreadsAt_SimulationIO__Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_SimulationIO__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_SimulationIO__Framework__Global;
	}
	void CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_SimulationIO__Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SimulationIO__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SimulationIO__Framework();
	}
	void CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_SimulationIO__Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SimulationIO__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SimulationIO__Global();
	}
	CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__App* CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SimulationIO__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_SimulationIO__App();
	}
	CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Global* CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SimulationIO__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_SimulationIO__Global();
	}
	void CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SimulationIO__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SimulationIO__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SimulationIO__Global();
	}
	void CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SimulationIO__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SimulationIO__App();
	}
	void CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SimulationIO__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SimulationIO__Global();
	}
// private.
	void CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SimulationIO__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_SimulationIO__Framework__App = nullptr;
	}
	void CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SimulationIO__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_SimulationIO__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SimulationIO__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_SimulationIO__Framework__App = new class CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_SimulationIO__App() == nullptr) {}
	}
	void CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SimulationIO__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_SimulationIO__Framework__Global = new class CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_SimulationIO__Global() == nullptr) {}
	}
	CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__App* CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_SimulationIO__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_SimulationIO__Framework__App;
	}
	CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Global* CLIBWriteQueAtSimulationIO::WriteEnableForThreadsAt_SimulationIO__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_SimulationIO__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_SimulationIO__Framework__Global;
	}