#include "WriteEnableForThreadsAt_Server_ConditionCode_Framework.h"
CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode__App* CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_ConditionCode__Framework__App;
	CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode__Global* CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_Server_ConditionCode__Framework__Global;
// public.
	CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::WriteEnableForThreadsAt_Server_ConditionCode_Framework() {

	}
	CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::~WriteEnableForThreadsAt_Server_ConditionCode_Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_ConditionCode__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_Server_ConditionCode__Framework__Global;
	}
	void CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::dyn_CLASS_create_Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Server_ConditionCode__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_ConditionCode__Framework();
	}
	void CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::dyn_CLASS_create_CLIB_OpenEpiCentre_Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Server_ConditionCode__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_ConditionCode__Global();
	}
	CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode__App* CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_Server_ConditionCode__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_ConditionCode__App();
	}
	CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode__Global* CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_Server_ConditionCode__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_ConditionCode__Global();
	}
	void CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Server_ConditionCode__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Server_ConditionCode__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Server_ConditionCode__Global();
	}
	void CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_ConditionCode__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_ConditionCode__App();
	}
	void CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_ConditionCode__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_ConditionCode__Global();
	}
// private.
	void CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Server_ConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_ConditionCode__Framework__App = nullptr;
	}
	void CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Server_ConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_Server_ConditionCode__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_ConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_ConditionCode__Framework__App = new class CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_ConditionCode__App() == nullptr) {}
	}
	void CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_ConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_Server_ConditionCode__Framework__Global = new class CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_ConditionCode__Global() == nullptr) {}
	}
	CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode__App* CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_ConditionCode__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_ConditionCode__Framework__App;
	}
	CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode__Global* CLIBWriteQueAtServer_ConditionCode::WriteEnableForThreadsAt_Server_ConditionCode_Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_ConditionCode__Global()
		{
			return _stat_CLASS_ptr_WriteEnableForThreadsAt_Server_ConditionCode__Framework__Global;
		}