#include "WriteEnableForThreadsAt_ClientUserInput__Framework.h"
CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__App* CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserInput__Framework__App;
	CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Global* CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientUserInput__Framework__Global;
// public.
	CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::WriteEnableForThreadsAt_ClientUserInput__Framework() {

	}
	CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::~WriteEnableForThreadsAt_ClientUserInput__Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserInput__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ClientUserInput__Framework__Global;
	}
	void CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ClientUserInput__Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientUserInput__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserInput__Framework();
	}
	void CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ClientUserInput__Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientUserInput__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserInput__Global();
	}
	CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__App* CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserInput__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserInput__App();
	}
	CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Global* CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserInput__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserInput__Global();
	}
	void CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientUserInput__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientUserInput__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientUserInput__Global();
	}
	void CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserInput__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserInput__App();
	}
	void CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserInput__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserInput__Global();
	}
// private.
	void CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientUserInput__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserInput__Framework__App = nullptr;
	}
	void CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientUserInput__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientUserInput__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserInput__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserInput__Framework__App = new class CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserInput__App() == nullptr) {}
	}
	void CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientUserInput__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientUserInput__Framework__Global = new class CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserInput__Global() == nullptr) {}
	}
	CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__App* CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserInput__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserInput__Framework__App;
	}
	CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Global* CLIBWriteQueAtClientUserInput::WriteEnableForThreadsAt_ClientUserInput__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientUserInput__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ClientUserInput__Framework__Global;
	}