#include "WriteEnableForThreadsAt_STACK__Framework.h"
#include "../include/WriteEnableForThreadsAt_STACK__Control.h"
#include <iostream>
CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__App* CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App;
CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Global* CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_STACK__Global;
// public.
CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::WriteEnableForThreadsAt_STACK__Framework()
{
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_STACK__Framework();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_STACK__Framework();
}
CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::~WriteEnableForThreadsAt_STACK__Framework()
{
	delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App;
	delete _stat_CLASS_ptr_WriteEnableForThreadsAt_STACK__Global;
}
CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__App* CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App();
}
CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Global* CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__Global() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__Global();
}
void CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_STACK__Framework(WriteEnableForThreadsAt_STACK__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App__Control()->dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_STACK__Control(obj);
}
void CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_STACK__Framework(WriteEnableForThreadsAt_STACK__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App__Control()->dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_STACK__Control(obj);
}
void CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_STACK__Framework(WriteEnableForThreadsAt_STACK__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App__Control()->dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_STACK__Control(obj);
}
void CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::dyn_boot4_PGM_INSTANTIATION_WriteEnableForThreadsAt_STACK__Framework(WriteEnableForThreadsAt_STACK__Framework* obj) {

}
void CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_STACK__Framework() {
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_STACK__App();
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_STACK__Global();
}
void CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_STACK__Framework() {
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_STACK__App();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_STACK__Global();
}
// private.
void CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_STACK__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App = nullptr;
}
void CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_STACK__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_STACK__Global = NULL;
}
void CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_STACK__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App = new class CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__App();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App() == nullptr) {}
}
void CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_STACK__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_STACK__Global = new class CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Global();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__Global() == NULL) {}
}
CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__App* CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App()
{
	return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__App;
}
CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Global* CLIBWriteQueAtSTACK::WriteEnableForThreadsAt_STACK__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_STACK__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_STACK__Global;
	}