#include "WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework.h"
CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__App* CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework__App;
	CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global* CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework__Global;
// public.
	CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework() {

	}
	CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::~WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework__Global;
	}
	void CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::dyn_CLASS_create_Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework();
	}
	void CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::dyn_CLASS_create_CLIB_OpenEpiCentre_Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global();
	}
	CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__App* CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__App();
	}
	CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global* CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global();
	}
	void CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global();
	}
	void CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__App();
	}
	void CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global();
	}
// private.
	void CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework__App = nullptr;
	}
	void CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework__App = new class CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__App() == nullptr) {}
	}
	void CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework__Global = new class CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global() == nullptr) {}
	}
	CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__App* CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework__App;
	}
	CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global* CLIBWriteQueAtServerAssembly_ConditionCode::WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Global()
		{
			return _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerAssembly_ConditionCode__Framework__Global;
		}