#include "WriteEnableForThreadsAt_ClientConditionCode__Framework.h"
CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__App* CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientConditionCode__Framework__App;
	CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Global* CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientConditionCode__Framework__Global;
// public.
	CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::WriteEnableForThreadsAt_ClientConditionCode__Framework() {

	}
	CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::~WriteEnableForThreadsAt_ClientConditionCode__Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientConditionCode__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ClientConditionCode__Framework__Global;
	}
	void CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ClientConditionCode__Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientConditionCode__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientConditionCode__Framework();
	}
	void CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ClientConditionCode__Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientConditionCode__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientConditionCode__Global();
	}
	CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__App* CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientConditionCode__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientConditionCode__App();
	}
	CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Global* CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ClientConditionCode__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientConditionCode__Global();
	}
	void CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientConditionCode__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientConditionCode__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientConditionCode__Global();
	}
	void CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientConditionCode__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientConditionCode__App();
	}
	void CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientConditionCode__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientConditionCode__Global();
	}
// private.
	void CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientConditionCode__Framework__App = nullptr;
	}
	void CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ClientConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientConditionCode__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientConditionCode__Framework__App = new class CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientConditionCode__App() == nullptr) {}
	}
	void CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ClientConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ClientConditionCode__Framework__Global = new class CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientConditionCode__Global() == nullptr) {}
	}
	CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__App* CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientConditionCode__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientConditionCode__Framework__App;
	}
	CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Global* CLIBWriteQueAtClientConditionCode::WriteEnableForThreadsAt_ClientConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ClientConditionCode__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ClientConditionCode__Framework__Global;
	}