#include "WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework.h"
CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__App* CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework__App;
	CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global* CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework__Global;
// public.
	CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework() {

	}
	CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::~WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework__Global;
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::dyn_CLASS_create_Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework();
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::dyn_CLASS_create_CLIB_OpenEpiCentre_Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global();
	}
	CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__App* CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__App();
	}
	CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global* CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global();
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global();
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__App();
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global();
	}
// private.
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework__App = nullptr;
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework__App = new class CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__App() == nullptr) {}
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework__Global = new class CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global() == nullptr) {}
	}
	CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__App* CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework__App;
	}
	CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global* CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Global()
		{
			return _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerLaunchQue_ConditionCode__Framework__Global;
		}