#include "WriteEnableForThreadsAt_InputPerihperalSamples__Framework.h"
#include "../include/WriteEnableForThreadsAt_InputPerihperalSamples__Control.h"
#include <iostream>
CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__App* CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App;
CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Global* CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__Global;
// public.
CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::WriteEnableForThreadsAt_InputPerihperalSamples__Framework()
{
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_InputPerihperalSamples__Framework();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_InputPerihperalSamples__Framework();
}
CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::~WriteEnableForThreadsAt_InputPerihperalSamples__Framework()
{
	delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App;
	delete _stat_CLASS_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__Global;
}
CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__App* CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App();
}
CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Global* CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__Global() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__Global();
}
void CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_InputPerihperalSamples__Framework(WriteEnableForThreadsAt_InputPerihperalSamples__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App__Control()->dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_InputPerihperalSamples__Control(obj);
}
void CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_InputPerihperalSamples__Framework(WriteEnableForThreadsAt_InputPerihperalSamples__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App__Control()->dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_InputPerihperalSamples__Control(obj);
}
void CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_InputPerihperalSamples__Framework(WriteEnableForThreadsAt_InputPerihperalSamples__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App__Control()->dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_InputPerihperalSamples__Control(obj);
}
void CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::dyn_boot4_PGM_INSTANTIATION_WriteEnableForThreadsAt_InputPerihperalSamples__Framework(WriteEnableForThreadsAt_InputPerihperalSamples__Framework* obj) {

}
void CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_InputPerihperalSamples__Framework() {
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_InputPerihperalSamples__App();
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_InputPerihperalSamples__Global();
}
void CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_InputPerihperalSamples__Framework() {
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_InputPerihperalSamples__App();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_InputPerihperalSamples__Global();
}
// private.
void CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_InputPerihperalSamples__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App = nullptr;
}
void CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_InputPerihperalSamples__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__Global = NULL;
}
void CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_InputPerihperalSamples__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App = new class CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__App();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App() == nullptr) {}
}
void CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_InputPerihperalSamples__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__Global = new class CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Global();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__Global() == NULL) {}
}
CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__App* CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App()
{
	return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__App;
}
CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Global* CLIBWriteQueAtInputPerihperalSamples::WriteEnableForThreadsAt_InputPerihperalSamples__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_InputPerihperalSamples__Global;
	}